# Generated by Django 3.2.7 on 2021-10-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordetails',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='donordetails',
            name='phone_number',
            field=models.IntegerField(max_length=20),
        ),
    ]
