# Generated by Django 3.2.7 on 2021-10-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_bank_app', '0002_auto_20211001_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordetails',
            name='age',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='donordetails',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
